### ISSUE TITLE
An error occured while Gow tried to handle your request: app failed to bind

### ISSUE THREAD

**Issue by chrise86** [jonasschneider/gow#4]
I managed to get it installed on `Mac OSX 10.11`, `Go 1.5.1` by changing:

```
go install github.com/jonasschneider/gow
```

to:

```
go get github.com/jonasschneider/gow
```

but now I get the above error when loading a .dev domain after linking.

**Comment by jonasschneider** [comment]
Hi, could you post your `~/Library/Logs/gowd.log`? (It's possible that it contains startup messages from your app, if so, you might want to create a private Gist)

**Comment by chrise86** [comment]
That was quick!

Here is log https://gist.github.com/chrise86/f8a698e20f9db0b5a4f4

**Comment by jonasschneider** [comment]
Thanks. Your server is `Listening on localhost:4000`, not the port that Gow wants it to listen on (the numbers printed in the log, like `49587`). I think you'll need to add something like `-p $PORT` to your `Procfile`! :)

**Comment by chrise86** [comment]
Awesome thanks very much! :smile:
